site_name: FoodBack
site_description: DocumentaÃ§Ã£o oficial do projeto FoodBack

theme:
  name: material
  language: pt-BR

  palette:
    - scheme: default
      primary: custom
      accent: green
      toggle:
        icon: material/weather-night
        name: Modo escuro
      colors:
        primary: "#00A86B"
        accent: "#6BEFA3"

    - scheme: slate
      primary: custom
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Modo claro
      colors:
        primary: "#00915E"
        accent: "#4EDC84"

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    logo: material/pizza

  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - content.footnotes
    - content.tooltips

extra_css:
  - stylesheets/extra.css

nav:
  - "ğŸ  InÃ­cio": index.md
  - "ğŸ“˜ DescriÃ§Ã£o Geral": descricao.md
  - "âš ï¸ Problema Identificado": problema.md
  - "ğŸ’¡ Justificativa": justificativa.md
  - "ğŸ¯ PÃºblico-Alvo / UsuÃ¡rios": publico-alvo.md
  - "ğŸ Concorrentes": concorrentes.md
  - "âš™ï¸ SoluÃ§Ã£o / Funcionamento": solucao.md
  - "ğŸ§  Mapa de Empatia": empatia.md

  - "ğŸ§­ Jornada do UsuÃ¡rio":
      - "ğŸ­ Empresa Doadora": jornada-empresa.md
      - "ğŸ¤ ONG Receptora": jornada-ong.md

  - "ğŸ§° Tecnologias Utilizadas": tecnologias.md

  - "ğŸ“‘ Requisitos":
      - "ğŸ“‹ Funcionais e NÃ£o Funcionais": requisitos.md

  - "ğŸ’² Simulador Financeiro": financeiro.md
  - "ğŸš€ VisÃ£o de Futuro": futuro.md
  - "ğŸ¬ Pitch": pitch.md
  - "ğŸ§¾ ConsideraÃ§Ãµes Finais": consideracoes.md